### PR TITLE
Feature/update dependencies

### LINKED ISSUE #28: Use the new Tailwind JIT plugin
We should test if it is compatible with our workflow.

### PR DESCRIPTION
**Pull request by titouanmathis**
This PR introduces the following:

- Add a `mergeCSS` option to force concatenation of all initial CSS chunks (bb11146, 065af6f)
- Add a `__DEV__` global variable (27364df)
- Use hashed filenames in production for the prototyping preset (a432f8e)
- Add a JSON manifest file `assets-manifest.json` with all generated assets (533644a, ca83b60)
- Add the `postcss-preset-env` plugin to the default PostCSS configuration (66c705f)
- Add `WebpackBar` when starting the dev server (f6f5d58)
- Add support for the `.cjs` extension for the config file (0d96d3f)
- Add support for import of SVG file as Vue component with `?as-vue-component` resourceQuery (d4783c2, 171e201)
- Migrate to a workspace configuration (8d58f43)
- Add default configuration for the `babel-loader` (d7e6585, 904f0be)
- Add default configuration for ESLint and Stylelint (d758d43)
- Replace `file-loader` and `url-loader` by native asset rules (09badec)
- Replace the `CleanWebpackPlugin` with the native output.clean option (686977a)
- Update and clean NPM dependencies (d80fcbd, 3944c85, d8c50ef)
- Add a method to get the generated Webpack configuration (c23df9c)

These changes should help us towards closing #27 and will fix #28.

---

## Add a `mergeCSS` option to force concatenation of all initial CSS chunks

In the previous version, CSS from Vue components was kept in the generated JS files. This is not ideal, so we add a new `mergeCSS: boolean` options to the `meta.config.js` file to merge all initial CSS chunks into one single file. CSS imported in a dynamically imported module will be injected by Webpack when the module is loaded.

When enabled, this option will create a `styles.css` file at the root of the dist folder.

```js
// meta.config.js
module.exports = {
  mergeCSS: true,
};
```

## Add support for import of SVG file as Vue component with `?as-vue-component` resourceQuery

It is now possible to import SVG files as Vue components by appending `?as-vue-component` to their import path:

```js
import VueIcon from '../svg/icon.svg?as-vue-component';

export default {
  components: { 
    VueIcon,
    LazyVueIcon: () => import('../svg/lazy-icon.svg?as-vue-component'),
  }
}
```

## Default configurations for Babel, ESLint and StyleLint

The tool can now be used without having to create configuration for each of these tools and apply our own configurations. The default Babel configuration includes polyfills from `core-js@3`.

## Add a JSON manifest file `assets-manifest.json` with all generated assets

A JSON file is generated containing all assets emitted as well as assets related to entrypoints.

```json
{
  "entrypoints": {
    "css/app": {
      "assets": {
        "js": [
          "manifest.js",
          "vendors.js"
        ],
        "css": [
          "styles.css"
        ]
      }
    },
    "js/app": {
      "assets": {
        "js": [
          "manifest.js",
          "vendors.js",
          "js/app.js"
        ],
        "css": [
          "styles.css"
        ]
      }
    }
  },
}
```

This addition should help us when using the generated assets with a backend CMS (WordPress, Drupal, etc.) as this file could be parsed to gather the files to include.

### CODE REVIEW

**Review by notjb — APPROVED** [review]
Seems good to me ! 🎸

**Comment by titouanmathis** [comment]
@notjb I removed the breaking change by adding a new `mergeCSS` option disabled by default. 

The package can be tested with the `next` tag:

```sh
npm install -D @studiometa/webpack-config@next
```

**Review by perruche — APPROVED** [review]
👍 , defaut config files for linting is great !

**Comment by perruche** [comment]
Does the `mergeCSS` allow file exceptions ? 
For exemple exclude a custom admin back office style to be merged

**Comment by notjb** [comment]
The demo is working smoothly.
How about adding a README.md file at the demo's root with the following : 

```
# Demo
This package works with npm workspaces ([see the documentation](https://docs.npmjs.com/cli/v7/using-npm/workspaces)), therefore in order to install and try the demo, do as follow : 
- go to the package's root
- run `npm install`
- run `npm run dev --workspace=@studiometa/webpack-config-demo`
- The demo is by default running on `localhost:3000`
```
--
🦄

**Comment by titouanmathis** [comment]
> Does the `mergeCSS` allow file exceptions ?
> For exemple exclude a custom admin back office style to be merged

It does not, but it should! I will look into it before merging.

>  How about adding a README.md file at the demo's root 

Good idea, will do 😉

**Comment by titouanmathis** [comment]
@notjb the README is in place for the demo 😉 

@perruche It is now possible to exclude some CSS files from being merged when the `mergeCSS` option is enabled by specifying a RegExp or a function instead of a boolean:

```js
module.exports = {
  mergeCSS: /^(?!.*css\/test\.scss).*$/,
  // or
  mergeCSS: (module, chunk) => 
    module.constructor.name === 'CssModule'
    && !module.userRequest.endsWith('css/test.scss'),
}
```

When using a RegExp or a function, the value will be assigned to the `test` property of the styles cache group, you can check the [official documentation](https://webpack.js.org/plugins/split-chunks-plugin/#splitchunkscachegroupscachegrouptest) for more information.

**Pull request merged**
